"""empty message

Revision ID: 47c32f480bbe
Revises: 
Create Date: 2019-10-09 15:37:05.511594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c32f480bbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_tmdb_id_key', 'movies', type_='unique')
    op.alter_column('rating', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('movies_tmdb_id_key', 'movies', ['tmdb_id'])
    # ### end Alembic commands ###
