"""empty message

Revision ID: 5492026ebb08
Revises: 47c32f480bbe
Create Date: 2019-10-09 23:48:11.128984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5492026ebb08'
down_revision = '47c32f480bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
