"""empty message

Revision ID: b1d485e00963
Revises: 5492026ebb08
Create Date: 2019-10-10 00:12:16.082995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1d485e00963'
down_revision = '5492026ebb08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.drop_column('session', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('session', 'created_date')
    # ### end Alembic commands ###
